### PR TITLE
Remove community.kubernetes from Ansible 6

### PR DESCRIPTION
**Pull request by felixfontein**

### CODE REVIEW

**Review by mariolenz — APPROVED** [review]
@felixfontein thanks for implementing this!

**Review by Andersson007 — APPROVED** [review]
@felixfontein LGTM, thanks for doing this!

There's a comment in ansible.in
>community.kubernetes shall be renamed to kubernetes.core, they are already the same build artifact
>https://github.com/ansible-collections/community.kubernetes/issues/221"

Should it be removed also it seems to make no sense now?

I'm also OK with keeping it, just wanted to spot

Anyway LGTM

**Comment by Andersson007** [comment]
@felixfontein thanks for removing!
@mariolenz thanks for reviewing!

**Comment by felixfontein** [comment]
@mariolenz @Andersson007 thanks for reviewing and merging!

**Pull request merged**
