### PR TITLE
Add 4.2.0 changelog fragment for community.kubernetes deprecation

### PR DESCRIPTION
**Pull request by felixfontein**
CC @jillr @gravesm can you please take a look at the wording? Thanks :)

### CODE REVIEW

**Review by jillr — APPROVED** [review]
LGTM, Mike has final say.

**Review by gravesm — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
I think it's best to keep this open until relatively close to the release of Ansible 4.2.0. Just in case there's suddenly a need to release 4.1.1 inbetween :)

CC @abadger

**Comment by felixfontein** [comment]
Merging since the 4.2.0 release is coming up this week.

**Pull request merged**
