### PR TITLE
Detail about playbook conditionals from changelog

### PR DESCRIPTION
**Pull request by oraNod**
This change manually includes details from the 2.17.0 changelog that were not included in the porting guide.

Relates to https://github.com/ansible/ansible-documentation/pull/1523

### CODE REVIEW

**Review by felixfontein — CHANGES_REQUESTED** [review]
This has to be fixed in ansibe/ansible-documentation, not here.

**Review by felixfontein — APPROVED** [review]
Ah, I just saw it's already merged there.

**Comment by samccann** [comment]
Just curious - what happens to this manual patch when 10.1.0 is released? Will it still show up?

**Comment by felixfontein** [comment]
It should stay, since by then this part is replaced by the part in ansible-documentation (either stable-2.17 branch or devel, I would have to check the code), and it's included in there as well.

**Comment by felixfontein** [comment]
@oraNod thanks!

**Pull request merged**
