### PR TITLE
[WIP] Restrict community.okd to 1.0.0 for Ansible 2.10

### PR DESCRIPTION
**Pull request by felixfontein**
I've added a changelog entry for this change explaining it. 

Before this is done, I have to test how antsibull-build reacts on an existing changelog for a new version. This might either require a fix to antsibull, or some more manual work during release. (Since this should be easier in the future, I prefer a fix to antsibull). Or maybe it already works as expected, I haven't tried this for a long time :)

### CODE REVIEW

**Comment by felixfontein** [comment]
First step for improving the release process was ansible-community/antsibull-changelog#51. The next step will be using that flag in antsibull (once a new version of antsibull-changelog is released).

**Comment by felixfontein** [comment]
The second step is ansible-community/antsibull#246, once that's merged this PR is no longer a WIP.

**Comment by abadger** [comment]
The antsibull pr has been merged. Now meeting this as well

**Comment by felixfontein** [comment]
@abadger thanks!

**Pull request merged**
