### PR TITLE
Add community.sops Ansible Collection

### PR DESCRIPTION
**Pull request by tadeboro**
Application and reviews are available at https://github.com/ansible-collections/ansible-inclusion/discussions/9

### CODE REVIEW

**Comment by felixfontein** [comment]
This needs to wait until we released a new version of community.sops. @endorama do you want to do that? I can also do it over the weekend.

**Comment by endorama** [comment]
On it!

**Comment by endorama** [comment]
`1.0.3` released, waiting for Zuul to pick it up!

**Comment by felixfontein** [comment]
1.0.3 is available on galaxy: https://galaxy.ansible.com/community/sops

**Review by gundalow — APPROVED** [review]

**Review by dmsimard — APPROVED** [review]

**Comment by dmsimard** [comment]
LGTM and I don't see any objections, community.sops will be in 3.0 :tada:

**Comment by endorama** [comment]
Thanks a lot everyone!

**Pull request merged**
