### PR TITLE
Ansible 7.0.0: Dependencies, changelog and porting guide

### PR DESCRIPTION
**Pull request by rooftopcellist**

### CODE REVIEW

**Review by felixfontein — CHANGES_REQUESTED** [review]
As commented on IRC, there's no entry in 7/changelog.yaml, which causes the changelog to be incorrect (wrong release date). (The changelog is also included in the tarball BTW.)

**Review by Ompragash — CHANGES_REQUESTED** [review]
@rooftopcellist I auto-generated the 7/CHANGELOG-v7.rst and 7/changelog.yaml with the below command and updated those changes on your pr branch [here](https://github.com/rooftopcellist/ansible-build-data/pull/1). Also, as Felix mentioned the tarball contains the outdated changelog.  
```
antsibull-build changelog --data-dir=./7 7.0.0
```

**Review by felixfontein — APPROVED** [review]

**Comment by rooftopcellist** [comment]
@Ompragash thank you for the patch.  I just merged it into my PR.  I was able to generate the changelog.yaml diff by re-running the build-single-release.yaml without `-e "antsibull_data_reset=false"`. It looks like the date didn't get updated in the CHANGELOG-v7.rst though oddly.

I re-built the .whl and .tar.gz so that it has the correct changelog.yaml in it. I did it with antsibull-build directly.

```
antsibull-build rebuild-single 7.0.0 --data-dir ansible-build-data/7 --build-file ansible-7.build --deps-file ansible-7.0.0.deps
```

**Review by Ompragash — APPROVED** [review]

**Comment by rooftopcellist** [comment]
FYI, the command @Ompragash shared to generate/update the changelog files didn't work for me for some reason.  So these are the steps I ended up taking:

1. copy 7.0.0rc1.deps --> 7.0.0.deps, same for the associated .yaml file
2. run build-single-release.yaml with -e "antsibull_data_reset=false"
3. staged and committed changes
4. run it again without -e "antsibull_data_reset=false" to generate the changelog.yaml
5. commit the changelog.yaml
6. delete the .whl and .tar.gz that were built and build them again now that the changelog.yaml is updated:
```
antsibull-build rebuild-single 7.0.0 --data-dir ansible-build-data/7 --build-file ansible-7.build --deps-file ansible-7.0.0.deps
```

There's probably a better way to have done this. But this works for now.

**Comment by gotmax23** [comment]
@Ompragash said:

```
antsibull-build changelog --data-dir=./7 7.0.0
```

As @felixfontein mentioned to me on IRC, separately running `antsibull-build changelog` isn't necessary. Minus that, I ended up doing

1. Copy over the deps files: `cp ansible-7.0.0{rc1,}.yaml && cp ansible-7.0.0{rc1,}.deps`
2. Edit `_ansible_version` in ansible-7.0.0.deps: something like `sed -i 's|^_ansible_version:.*$|_ansible_version: 7.0.0'` or manually
3.  Manually insert the changelog entry into changelog.yaml:

``` yaml
  7.0.0:
    changes:
      release_summary: 'Release Date: 2022-11-22
        `Porting Guide <https://docs.ansible.com/ansible/devel/porting_guides.html>`_'
    release_date: '2022-11-22'
```
4. Run the release playbook with `-e antsibull_data_reset=False`.

Hopefully, we can add native support for this to antsibull so you don't have to result to these type of workarounds next cycle.

**Comment by rooftopcellist** [comment]
Awesome, thank you for sharing that @gotmax23 !

**Comment by Ompragash** [comment]
@gotmax23 FYI: It isn't necessary but it comes to the rescue to generate `CHANGELOG*` and `porting guide*` in the worst case!

**Comment by gotmax23** [comment]
Yeah, it is useful in some cases. I just used it, because I wanted to verify my changelog entries in https://github.com/ansible-community/ansible-build-data/pull/183 were formatted correctly but not build the entire ansible distribution :).

**Pull request merged**
