### PR TITLE
Remove cisco.asa from Ansible 12

### LINKED ISSUE #508: Schedule cisco.asa from Ansible 12
We should deprecate cisco.asa in Ansible 11 and scheduled it for removal from Ansible 12. See https://forum.ansible.com/t/deprecation-announcement-for-the-cisco-asa-ansible-collection/38939. As per https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_package_removal.html#removing-a-collection-that-has-been-explicitly-deprecated-or-abandoned-by-its-former-maintainers, this can be done without an SC vote.

### PR DESCRIPTION
**Pull request by mariolenz**
Fixes #508

The collection has been deprecated.

See also https://forum.ansible.com/t/38960

### CODE REVIEW

**Review by felixfontein — APPROVED** [review]
Looks correct to me.

**Review by Andersson007 — APPROVED** [review]

**Review by gotmax23 — APPROVED** [review]

**Comment by mariolenz** [comment]
Since there are no objections in the forum thread but two approvals here, I think we should merge this.

@Andersson007 @felixfontein @gotmax23 Thanks for reviewing!

**Comment by notesbytom** [comment]
I disagree with the decision to remove the cisco.asa collection. Cisco ASA software is supported on the very latest Cisco Firewall hardware and virtual platforms. New releases are being developed with new features for example the latest release train is 9.22.x which first shipped in September 2024. Ansible is one of the best ways to automate management of the Cisco ASA. See my detailed comments under [issue 508](https://github.com/ansible-community/ansible-build-data/issues/508).

**Comment by mariolenz** [comment]
> I disagree with the decision to remove the cisco.asa collection. Cisco ASA software is supported on the very latest Cisco Firewall hardware and virtual platforms.

The decision to remove the collection from the [Ansible Community Package](https://pypi.org/project/ansible/) has _nothing_ to do with Cisco supporting ASA or not. We'll remove the collection because we have been informed that _the collection_ is deprecated.

As long as [the maintainers of the collection don't change their mind, or someone else steps up to maintain the collection](https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_package_removal.html#canceling-removal-of-an-unmaintained-collection), I don't think we will undo this. You'll still be able to install the collection via `ansible-galaxy`, though, but I'm not really sure if it's a good idea to depend on deprecated software...

I suggest to not spam multiple GitHub issues and forum threads with this, but discuss this in [Deprecation Announcement for the cisco.asa Ansible Collection](https://forum.ansible.com/t/38939). At he end of the day, as long as the collection is deprecated I think we'll keep to our decision to remove it from the Ansible community package (_not galaxy!_).

**Pull request merged**
