### PR TITLE
Add purestorage.fusion to ansible 6

### PR DESCRIPTION
**Pull request by Andersson007**
Relates to https://github.com/ansible-community/community-topics/issues/117

### CODE REVIEW

**Comment by gotmax23** [comment]
https://github.com/ansible-community/ansible-build-data/pull/142 fixes the broken CI.

**Review by Ompragash — APPROVED** [review]

**Comment by Andersson007** [comment]
@Ompragash @gotmax23 @felixfontein should we exclude testing against Ansible 5 by the way?

**Comment by Andersson007** [comment]
Created a PR https://github.com/ansible-community/ansible-build-data/pull/143

**Comment by Ompragash** [comment]
Addressed on Matrix and #143 is. merged now!
Thanks @Andersson007

**Pull request merged**
