### PR TITLE
Add community.sap to Ansible 5 and 6's ansible.in files

### PR DESCRIPTION
**Pull request by Andersson007**
Add community.sap to Ansible 5 and 6's ansible.in files

Implements https://github.com/ansible-community/community-topics/issues/74

### CODE REVIEW

**Comment by Andersson007** [comment]
failed: [localhost] (item=community.sap) => {
    "ansible_loop_var": "item",
    "assertion": "item in _installed_collections.stdout",
    "changed": false,
    "evaluated_to": false,
    "item": "community.sap",
    "msg": "community.sap is in ansible.in but not inside the package. Maybe run 'antsibull-build new-ansible --data-dir=/home/runner/work/ansible-build-data/ansible-build-data/antsibull/build/ansible-build-data/5' to update ansible.in and then rebuild ?"
}

**Comment by Andersson007** [comment]
@dmsimard I did it `The version is 1.0.0 right now so the line would probably look like this: community.sap: >=1.0.0,<2.0.0`. It didn't help

**Comment by dmsimard** [comment]
@Andersson007 fixed by https://github.com/ansible-community/ansible-build-data/pull/105, I've tested it in https://github.com/ansible-community/ansible-build-data/pull/104.

Once 105 merges, we should be able to land this PR once we've added the changes to the .build files back in.

**Comment by Andersson007** [comment]
@dmsimard , added the file back, thanks!

**Comment by dmsimard** [comment]
> You still have to manually add it to 5/ansible-5.build. And I really think that the 6/ansible-5.build should be deleted, it does not belong in this repo until we start releasing 6.x.y.

Having the ansible-6.build file in the repo allows us to test it ahead of time, I'd like to keep it.

**Comment by felixfontein** [comment]
@dmsimard but what exactly do you need it for? The tests in CI obviously do **not** need that file, because they create it automatically when it's not there. (The Ansible 6 build tests passed when the file was deleted.)

**Comment by felixfontein** [comment]
I've created a separate PR to delete this file, #106. As you can see CI passes, it really does not need this file.

**Comment by Andersson007** [comment]
cc @dmsimard

**Review by felixfontein — APPROVED** [review]

**Comment by dmsimard** [comment]
> @dmsimard but what exactly do you need it for? The tests in CI obviously do **not** need that file, because they create it automatically when it's not there. (The Ansible 6 build tests passed when the file was deleted.)

Ah, right, it does create the file when it doesn't exist.

**Comment by Andersson007** [comment]
Thanks folks!

I added a short manual on how to do this to README, could you please take a look? https://github.com/ansible-community/ansible-build-data/pull/108

**Pull request merged**
