### PR TITLE
Ansible 7.0.0a1: Dependencies, changelog and porting guide

### PR DESCRIPTION
**Pull request by rooftopcellist**

### CODE REVIEW

**Review by felixfontein — APPROVED** [review]

**Review by Ompragash — APPROVED** [review]

**Comment by felixfontein** [comment]
This needs to be rebased / recreated based on current `main`.

**Comment by rooftopcellist** [comment]
I rebased the main branch, installed antsibull from the latest changes, and recreated this PR by running the build-single-release.yml playbook again.  

Thanks for the help @felixfontein !

**Review by felixfontein — APPROVED** [review]
The Python 3.9 breaking change is now part of the changelog (https://github.com/ansible-community/ansible-build-data/pull/163/files#diff-7b296616a7bbd07880ba1754539ab97bc124ea41a1a2018318f4854a6aa9790cR1193) and of the porting guide, so LGTM!

**Comment by Ompragash** [comment]
Thanks for the PR @rooftopcellist!

**Pull request merged**
