### PR TITLE
Add kubevirt.core to Ansible 10 and 11

### PR DESCRIPTION
**Pull request by felixfontein**
Second try, after original PR #419 and revert #432.

Waits for https://github.com/kubevirt/kubevirt.core/issues/110 to be resolved.

### CODE REVIEW

**Comment by felixfontein** [comment]
I would wait until there is a new release.

**Comment by 0xFelix** [comment]
There is a new release https://github.com/kubevirt/kubevirt.core/releases/tag/1.5.0 :)

**Comment by mariolenz** [comment]
@felixfontein Does 1.5.0 look OK to you? If it does, I think you might want to change `kubevirt.core: >=1.4.0,<2.0.0` to `kubevirt.core: >=1.5.0,<2.0.0` and merge.

**Review by mariolenz — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
@mariolenz thanks for reviewing!
@0xFelix thanks for pinging about the release!

**Comment by 0xFelix** [comment]
What would be the appropriate Ansible version to include the next major release of `kubevirt.core`? Version `2.0.0` is out. :)

**Comment by mariolenz** [comment]
Since it's a new _major_ release of the collection, it won't be included in Ansible 10. But it should be included in the next _major_ Ansible release, which will be 11, automatically.

**Comment by 0xFelix** [comment]
@mariolenz Thanks for the update

**Pull request merged**
