### PR TITLE
github ci: test builds for both ansible 5 and 6

### PR DESCRIPTION
**Pull request by dmsimard**

### CODE REVIEW

**Comment by dmsimard** [comment]
Ah, it's failing because we've changed ``_ansible_base`` to ``_ansible_core`` in the ansible.in/deps file. The role currently checks for ``_ansible_base`` so it would need to support both unless we change the string across every file.

I sent a change to antsibull so we can check for both: https://github.com/ansible-community/antsibull/pull/362

**Comment by felixfontein** [comment]
With that PR merged, tests pass :)

**Comment by felixfontein** [comment]
@dmsimard thanks for improving the tests!

**Comment by dmsimard** [comment]
@felixfontein thanks for reviewing both PRs :)

**Pull request merged**
