### PR TITLE
[WIP] Cancel deprecation of netapp.storagegrid

### PR DESCRIPTION
**Pull request by felixfontein**
Depends on https://forum.ansible.com/t/2811/24

Needs https://github.com/ansible-community/antsibull-core/pull/177 and https://github.com/ansible-community/antsibull-build/pull/640 and https://github.com/ansible-community/antsibull-docs/pull/352.

This will not modify the existing changelogs, and add the following entries:
- 9.12.0:
  ```yaml
  major_changes:
    - The removal of netapp.storagegrid was cancelled. The collection will not be removed from Ansible 11.
  ```
- 10.6.0:
  ```yaml
  major_changes:
    - The removal of netapp.storagegrid was cancelled. The collection will not be removed from Ansible 11.
  ```
- 11.0.0b1:
  ```yaml
  major_changes:
    - The previously removed collection netapp.storagegrid was re-added to Ansible 11.
  ```

### CODE REVIEW

**Comment by felixfontein** [comment]
I'd like to improve the new changelog entries (like including the link to the discussion), but let's do that in the future and not for now. The timeline's already way too tight for all the releases on Tuesday.

**Comment by mariolenz** [comment]
I agree we it might be hard to implement this properly because there's not enough time. But how should we cancel the deprecation / re-add `netapp.storagegrid` if https://forum.ansible.com/t/2811/24 is accepted?

Would #489 would be OK?

**Comment by felixfontein** [comment]
#489 is kind of the minimal version to re-add it; this PR is a better version (but requires tooling support from antsibull-core and antsibull-build, and also antsibull-docs so that Ansible 9 and 10 stop saying it will be removed from Ansible 11).

**Comment by mariolenz** [comment]
> this PR is a better version (but requires tooling support from antsibull-core and antsibull-build, and also antsibull-docs

Yes, that's the problem. If we agree to re-add / cancel the deprecation, do we get this support in time for tomorrow? Or should we do it quick'n'dirty like in #489?

If we get this support in time, I'm fine with closing my PR and use this one :-)

**Comment by felixfontein** [comment]
If I get the PRs reviewed until I get up tomorrow morning and only small changes (or none) are required, we can get support for this by then. If not, then not. In that case we should merge your PR; we can still improve the situation later with this PR in a rebased form. But first of all we need a vote for not removing the collection; so far with 3 SC votes it doesn't look so good :(

**Comment by felixfontein** [comment]
(I'll do an antsibull-build release tomorrow morning no matter whether the new PRs get merged or not, to get the changelog editing feature out.)

**Comment by felixfontein** [comment]
Closing since the removal was not cancelled. See https://forum.ansible.com/t/2811/28 for details.

**Pull request closed without merging**
