### PR TITLE
Revert "Restrict ansible.utils to < 4.0.0 for now. (#382)"

### PR DESCRIPTION
**Pull request by felixfontein**
This reverts commit d10d57b25884b79ffb4c0ccdd9c6a0ef71f39f33.

All three collections released new versions.

### CODE REVIEW

**Review by mariolenz — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
The cisco.meraki 2.18.0 release has no tag, that's why the build fails. I've reported it in https://github.com/meraki/dashboard-api-ansible/issues/49, I hope it will be fixed soon.

**Comment by felixfontein** [comment]
The 2.18.0 tag is there now (https://github.com/meraki/dashboard-api-ansible/tags); I re-triggered the failed runs.

**Comment by felixfontein** [comment]
And tests passed :tada: Right in time for tomorrow's 10.0.0a1 release!

**Pull request merged**
